interface:
  auth:  # 用户登录模块
    - url: /v1/access_token
      name: 获取token  # 接口注释
      className: QBInterface_auth   # 接口类名
      funName:
      - test_login_token: {  # 接口方法名
        bar: {'account': '61AAF941-1385-A83E-12C0-F9A2C41B1C1E', 'pass': 'yRZN3XBoKWV5p2zm9Pf7ICDA8xQdghOk'},
        test_data: {},     #时间
        case_name: 获取token,
        result: [200],         # 预期结果
        mode: post,          # 请求类型
        re_bar: data,        # 请求参数
      }
    - url: /api/v/1.0/click
      name: 好友邀请   # 接口注释
      className: QBfriend_auth  # 接口类名
      funName:
      - test_auth_QBfriend: {  # 接口方法名
        bar: {'page':'invite_friend'},
        test_data: {},
        case_name: 获取短信验证码,
        result: [401],      # 预期结果
        mode: get,       # 请求方式
        re_bar: data,     # 请求参数
        }
    - url: /api/v/1.0/auth/sms_codes
      name: 获取短信验证码   # 接口注释
      className: ZYlogin_auth  # 接口类名
      funName:
      - test_auth_ZYlogin: {  # 接口方法名
        bar: {'mobile':'15882438611'},
        test_data: {},
        case_name: 获取短信验证码,
        result: [200],      # 预期结果
        mode: post,       # 请求方式
        re_bar: data,     # 请求参数
        }
    - url: /api/v/1.0/auth/access_token
      name: 获取token  # 接口注释
      className: ZYAccessToken_auth   # 接口类名
      funName:
      - test_auth_ZYAccessToken: {  # 接口方法名
        bar: {'mobile':'15882438611', 'code':'1234', 'os':'ios'},
        test_data: {},
        case_name: 获取token,
        result: [200],         # 预期结果
        mode: post,          # 请求类型
        re_bar: data,        # 请求参数
      }
    - url: /api/v/1.0/recharges
      name: 充值接口  # 接口注释
      className: ZYrecharge_auth   # 接口类名
      funName:
      - test_auth_ZYrecharge: {  # 接口方法名
        bar: {},
        test_data: {},
        case_name: 获取token,
        result: [200],         # 预期结果
        mode: get,          # 请求类型
        re_bar: data,        # 请求参数
      }
